// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwhicfgtakcpiedtdiqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3aGljZmd0YWtjcGllZHRkaXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MTAzNTgsImV4cCI6MjA2NDQ4NjM1OH0.Dy9LSvgXsl02bRBDlGFs4q1JzjDZD4NCMaS7w5aKMqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);